### ISSUE TITLE
Item lost at checkout page

### ISSUE THREAD

**Issue by blackyzero** [vendure-ecommerce/storefront-remix-starter#10]
Hello,

Another issue i am facing at checkout page, after inputing user email, first name and last name, then press "Tab" button to continue filling Shipping info, then the item was removed in "Order Summary"
Please see screenshot for more detail.

1) before pressing tab to move to shipping info

<img width="1675" alt="Screen Shot 2022-06-12 at 10 37 04 AM" src="https://user-images.githubusercontent.com/4286063/173238388-e6d9557b-9f14-4250-8e49-cf2e3d591baa.png">

2) pressed tab
<img width="1679" alt="Screen Shot 2022-06-12 at 10 37 14 AM" src="https://user-images.githubusercontent.com/4286063/173238397-f817e59c-6944-4cc9-ba22-14ab91b861c6.png">

Any idea how could i correct it?
Thank you.

**Comment by kyunal** [comment]
This looks like a session issue. Did you set the token method in your backend to `bearer` like the readme suggests?

**Comment by blackyzero** [comment]
You're right. I missed this setup. Now it works fine.
Thank you.
