### ISSUE TITLE
Customer account management

### ISSUE THREAD

**Issue by blackyzero** [vendure-ecommerce/storefront-remix-starter#14]
Hello,

This storefront is completely fast, really love it !
Would it be planed to add support for customer account management?

Thank you.

**Comment by michaelbromley** [comment]
Yes! It's right here in the "to do" section: https://github.com/vendure-ecommerce/storefront-remix-starter#to-do

I've not got an estimate of when I'll be able to work on that, though there are community members developing their storefront on this and it is quite likely they will contribute some work back in this area.

**Comment by michaelbromley** [comment]
Note: account registration flow was just implemented via https://github.com/vendure-ecommerce/storefront-remix-starter/pull/17

**Comment by blackyzero** [comment]
that's awesome new !!!
thank you @michaelbromley

**Comment by kyunal** [comment]
Hi, most customer account features are now implemented, thanks to these recent contributions:
- https://github.com/vendure-ecommerce/storefront-remix-starter/pull/30
- https://github.com/vendure-ecommerce/storefront-remix-starter/pull/34
- https://github.com/vendure-ecommerce/storefront-remix-starter/pull/37

There's some small things still missing (see our To Do section in the readme) but they aren't important for a lot of use cases. I'll close this issue for now.
