### ISSUE TITLE
Channels? (vendure multi-tenant) 

### ISSUE THREAD

**Issue by gnimmelf** [vendure-ecommerce/storefront-remix-starter#2]
Hello & congrats,

this repo was a nice surprise to discover.

Looking though the code and docs, I cannot find any setting for channel. 

Is there a way, per now, to configure using only one Vendure channel?

Cheers,
Flemming

**Comment by michaelbromley** [comment]
Hi! So the way to specify a particular Channel is by appending a `vendure-token` query string _or_ header to all your requests to the Shop API. i.e.
```
POST domain.com/shop-api?vendure-token=<my channel token>
```

More here: https://www.vendure.io/docs/storefront/shop-api-guide/#universal-parameters

**Comment by gnimmelf** [comment]
Yup, was on it when I found `app/graphqlWrapper.ts`. And it was as simple as it could be, so thanks for swift feedback and easily extendable code:

https://github.com/gnimmelf/eike-storefront-remix-starter/commit/4c3e775a53fc1eab019fe27c8a93e0377387803b
