### ISSUE TITLE
Add documentation on how to query custom fields

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/storefront-remix-starter#29]
See this discussion for the various steps which need to be documented:

- https://github.com/vendure-ecommerce/vendure/discussions/1924#discussioncomment-4342447

**Comment by kyunal** [comment]
I can take care of this and we can improve it as we go on. Is using the GitHub Wiki fine?

**Comment by michaelbromley** [comment]
I think there should also be something in the readme too to make it more discoverable. Perhaps a detailed guide in the wiki, and then a easy-to-find link to it from the readme would be good.

**Comment by kyunal** [comment]
Closed with https://github.com/vendure-ecommerce/storefront-remix-starter/wiki/Querying-custom-fields and https://github.com/vendure-ecommerce/storefront-remix-starter/commit/0134a3238d45fed246e373043852b184cbdeccf3
