### ISSUE TITLE
command not found 

### ISSUE THREAD

**Issue by ivan-vilches3** [vendure-ecommerce/storefront-remix-starter#31]
hello folks, when i run
npm run dev

i got this:
> dev
> concurrently "npm run dev:css" "remix dev"

sh: concurrently: command not found

**Comment by kyunal** [comment]
Did you run `npm install` first? What operating system and node/npm are you using?

**Comment by kyunal** [comment]
@ivan-vilches3 Is this issue still recent? I haven't been able to reproduce it.
