### ISSUE TITLE
Run in production mode in docker

### ISSUE THREAD

**Issue by robtec** [vendure-ecommerce/storefront-remix-starter#35]
Hi,

I'm trying to run this storefront in a docker container but I'm nor sure what `npm` goal I should be running to pickup the `.env` variables are run as production

Any help would be great

**Comment by robtec** [comment]
side-note, I'm using stripe as a payment backend

**Comment by kyunal** [comment]
Hi!

If you want to run the storefront inside a docker container you can use the build & start targets to get a production express server started. There are some projects that demonstrate how you can achieve this with a dockerfile, e.g. https://github.com/garand/remix-azure-docker

As for Stripe payments: You should just follow the instructions mentioned in the [Readme](https://github.com/vendure-ecommerce/storefront-remix-starter#stripe-integration) and use your live public key instead of the test public key. Be sure to do the same in the backend with your secret key.

If you come across some other issues I'm happy to assist!

**Comment by robtec** [comment]
So when I click

<img width="599" alt="Screenshot 2023-04-09 at 14 14 38" src="https://user-images.githubusercontent.com/8657653/230774870-1cdd68b7-2d56-40b9-88a5-a713657f2690.png">

I get

<img width="1150" alt="Screenshot 2023-04-09 at 14 14 27" src="https://user-images.githubusercontent.com/8657653/230774893-2c450bd4-fbba-425e-b850-9fe36d4a4591.png">

Guessing I'm missing something in the config?

**Comment by kyunal** [comment]
This sounds like the storefront is not using the `createStripePaymentIntent` mutation. How did you configure the stripe plugin and payment method in your backend? Does the payment method contain the word stripe in the payment method code?

**Comment by robtec** [comment]
I used the default storefront code, I didn't make any changes to the remix-storefront, the remix-storefront comes default with stripe working correct? or so I need to add some custom code to the storefront

**Comment by kyunal** [comment]
That is correct, on the frontend part you must just configure the publishable key as mentioned in the Readme. But the backend you use must enable the [Stripe Plugin](https://www.vendure.io/docs/typescript-api/payments-plugin/stripe-plugin/) and you must create a payment method that uses said Stripe Plugin. This isn't the case on a fresh vendure installation nor on the demo instance that the Remix Storefront will access on default.

**Comment by robtec** [comment]
So I have the backend configured

<img width="1004" alt="Screenshot 2023-04-12 at 21 26 47" src="https://user-images.githubusercontent.com/8657653/231576878-eac58698-1d09-4f41-ba87-942342d4f54d.png">

Also here is the `vendure-config.ts`

https://github.com/robtec/vendure-docker-deploy/blob/main/src/vendure-config.ts

Guessing I screwed up the config above

**Comment by kyunal** [comment]
Change the code in your screenshot from standard-payment to stripe and it should work. The storefront uses the payment code to determine which payment flow should be used

**Comment by robtec** [comment]
You are a legend! That worked, can't believe I never spotted that. Thank you 👍
