### ISSUE TITLE
Upgrading to Vendure 2.0

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/storefront-remix-starter#40]
Vendure v2.0 is in beta and will be released fairly soon. 

This issue is intended to collect notes on what needs to change in this project to support Vendure v2.

One I found so far:

[this line](https://github.com/vendure-ecommerce/storefront-remix-starter/blob/415448fa1509d478ca62dff0f2d71d401623e8ac/app/providers/orders/order.ts#L88) needs to change to:

```diff
gql`
-  mutation setOrderShippingMethod($shippingMethodId: ID!) {
+  mutation setOrderShippingMethod($shippingMethodId: [ID!]!) {
    setOrderShippingMethod(shippingMethodId: $shippingMethodId) {
      ...OrderDetail
      ... on ErrorResult {
        errorCode
        message
      }
    }
  }
`;
```

**Comment by kyunal** [comment]
How should we go about versioning? For now we could set up a V2 branch that, once V2 is officially out, we can merge into main.

I'm not sure whether or not we should preserve any V1 compatibility. I'm not even sure if it is important. I think it would be fine just linking the last commit & project tree before V2 support was merged, but that would mean no patches could be made by anybody concerned.

**Comment by DanielBiegler** [comment]
I personally think we shouldnt keep backwards compatability. In my mind this repo should be state of the art for Vendure so new people coming in always have a clean reference and demo with the latest features. I like linking to the last compatible v1 commit but not providing patches.

I'd just open a v2 branch after v2 officially drops and do everything in one swoop after the needed changes are finalized in this issue.

**Comment by michaelbromley** [comment]
Yeah I'd agree with just supporting the latest Vendure release on head. Since this is a "starter" rather than a library, the usage pattern would be to clone it at some point in time, and then just modify to your needs, after which point it belongs to you and you are in charge of maintaining & updating. Link to last v1 is a good idea though.

**Comment by zolzaya** [comment]
I'm using `vendure 2.0 beta` but I found an bug. When I go to the orders page, I get the following error. 

```
[1] Error: {"message":"Cannot query field \"fulfillments\" on type \"OrderLine\". Did you mean \"fulfillmentLines\"?","locations":[{"line":29,"column":11}]}
[1]     at /Users/zoloo/code/superb/storefront/app/graphqlWrapper.ts:109:13
[1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at loader12 (/Users/zoloo/code/superb/storefront/app/route-containers/account/orders.server.ts:27:8)
[1]     at Object.callRouteLoaderRR (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/server-runtime/dist/data.js:41:16)
[1]     at callLoaderOrAction (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/router/router.ts:3364:16)
[1]     at async Promise.all (index 0)
[1]     at loadRouteData (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/router/router.ts:2878:19)
[1]     at queryImpl (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/router/router.ts:2657:20)
[1]     at Object.queryRoute (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/router/router.ts:2597:18)
[1]     at handleDataRequestRR (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/server-runtime/dist/server.js:81:20)
[1] GET /account/orders?_data=routes%2Faccount%2Forders 500 - - 32.383 ms
```

how to fix?

**Comment by DanielBiegler** [comment]
@zolzaya This Storefront Template does not support v2 as of yet. Some internal data structures change between v1 and v2. For example in v1 you might get an Object and in v2 you might get an Array. If you want to use v2 you will have to fix all those differences yourself. Stuff like iterating or accessing non existing fields. When v2 drops I will look into that, probably, but for now youre on your own.

**Comment by dylviz** [comment]
> I'm using `vendure 2.0 beta` but I found a bug. When I go to the orders page, I get the following error.
> 
> ```
> [1] Error: {"message":"Cannot query field \"fulfillments\" on type \"OrderLine\". Did you mean \"fulfillmentLines\"?","locations":[{"line":29,"column":11}]}
> [1]     at /Users/zoloo/code/superb/storefront/app/graphqlWrapper.ts:109:13
> [1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> [1]     at loader12 (/Users/zoloo/code/superb/storefront/app/route-containers/account/orders.server.ts:27:8)
> [1]     at Object.callRouteLoaderRR (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/server-runtime/dist/data.js:41:16)
> [1]     at callLoaderOrAction (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/router/router.ts:3364:16)
> [1]     at async Promise.all (index 0)
> [1]     at loadRouteData (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/router/router.ts:2878:19)
> [1]     at queryImpl (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/router/router.ts:2657:20)
> [1]     at Object.queryRoute (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/router/router.ts:2597:18)
> [1]     at handleDataRequestRR (/Users/zoloo/code/superb/storefront/node_modules/@remix-run/server-runtime/dist/server.js:81:20)
> [1] GET /account/orders?_data=routes%2Faccount%2Forders 500 - - 32.383 ms
> ```
> 
> how to fix?

Any luck on this? I'm also seeing this

**Comment by zolzaya** [comment]
Hi, I'm fixed it. Here is the how:

On the `app/generated/graphql.ts` file remove code between `3892-3895`. Here is the removed code:
```
          fulfillments {
            updatedAt
            state
          }
```

Above code is not used in the frontend. So I removed it.

**Comment by dylviz** [comment]
> Hi, I fixed it. Here is the how:
> 
> On the `app/generated/graphql.ts` file remove code between `3892-3895`. Here is the removed code:
> 
> ```
>           fulfillments {
>             updatedAt
>             state
>           }
> ```
> 
> Above code is not used in the frontend. So I removed it.

Ahh! Very nice! Thanks!

**Comment by DanielBiegler** [comment]
@zolzaya @dylviz Removing code from the auto generated file doesnt really fix the root problem.

After generating types again, i.e. after you make an update or run codegen, it will break again because the types will be regenerated.

The types get generated because of here: https://github.com/vendure-ecommerce/storefront-remix-starter/blob/75eb880052d7f76b2026fc917cf545996012e3ac/app/providers/customer/customer.ts#L99-L102

Secondly, they are used in the `OrderHistoryItem` here https://github.com/vendure-ecommerce/storefront-remix-starter/blob/75eb880052d7f76b2026fc917cf545996012e3ac/app/components/account/OrderHistoryItem.tsx#L106-L114

The quick fix for if you dont need the fulfillment info is to

1. remove it from the customer `query activeCustomerOrderList`
2. rerun codegen
3. remove it from `OrderHistoryItem`

But remember that youre then branching off of this repo and will get conflicts when theres updates.

**Comment by dylviz** [comment]
> @zolzaya @dylviz Removing code from the auto generated file doesnt really fix the root problem.
> 
> After generating types again, i.e. after you make an update or run codegen, it will break again because the types will be regenerated.
> 
> The types get generated because of here:
> 
> https://github.com/vendure-ecommerce/storefront-remix-starter/blob/75eb880052d7f76b2026fc917cf545996012e3ac/app/providers/customer/customer.ts#L99-L102
> 
> Secondly, they are used in the `OrderHistoryItem` here
> 
> https://github.com/vendure-ecommerce/storefront-remix-starter/blob/75eb880052d7f76b2026fc917cf545996012e3ac/app/components/account/OrderHistoryItem.tsx#L106-L114
> 
> The quick fix for if you dont need the fulfillment info is to
> 
>     1. remove it from the customer `query activeCustomerOrderList`
> 
>     2. rerun codegen
> 
>     3. remove it from `OrderHistoryItem`
> 
> 
> But remember that youre then branching off of this repo and will get conflicts when theres updates.

It seems like a mismatch between the new backend type and the old frontend. I can see the backend Orderline doesn't have fulfillments anymore, but rather `fulfillmentLines: [FulfillmentLine!]` under type `OrderLine`

So it seems like the correct way to fix this would be to remove `fulfillment{}` as you suggested then utilize fulfillmentLines to try to pull the same info. Does that sound like the right path?

**Comment by zolzaya** [comment]
@DanielBiegler  you're right it's the quick fix.

**Comment by DanielBiegler** [comment]
> So it seems like the correct way to fix this would be to remove fulfillment{} as you suggested then utilize fulfillmentLines to try to pull the same info. Does that sound like the right path?

@dylviz Yes. But remember that there are more differences between v1 and v2. This is not the only change. You will run into further roadblocks later.

**Comment by dylviz** [comment]
> > So it seems like the correct way to fix this would be to remove fulfillment{} as you suggested then utilize fulfillmentLines to try to pull the same info. Does that sound like the right path?
> 
> @dylviz Yes. But remember that there are more differences between v1 and v2. This is not the only change. You will run into further roadblocks later.

We will get to know each other very well through all the debugging :) lol or are you trying to recommend that I wait for an update? I'm OK with either!

**Comment by kyunal** [comment]
> We will get to know each other very well through all the debugging :) lol or are you trying to recommend that I wait for an update? I'm OK with either!

I intend to get the starter ready before the Vendure V2 release. Also, V2 API changes are documented and discussed here: https://github.com/vendure-ecommerce/vendure/discussions/1991

---

cc @michaelbromley is there a demo instance for V2 yet? Or do you intend to upgrade the existing instance once V2 is out?

**Comment by DanielBiegler** [comment]
@michaelbromley hey there! Are the data structures for v2 finalized now? Or is there still a pending thing? Sry if that has been answered before, I havent seen it. If it's finalized I'd be down to port this storefront to v2 @kyunal

**Comment by michaelbromley** [comment]
Emphasis on the word "major" :D 

I cannot guarantee that there are no more breaks, but I don't predict any _major_ ones that would then require a significant amount of work.

**Comment by kyunal** [comment]
> @michaelbromley hey there! Are the data structures for v2 finalized now? Or is there still a pending thing? Sry if that has been answered before, I havent seen it. If it's finalized I'd be down to port this storefront to v2 @kyunal
> 
> Edit: Just seen the [new Video](https://www.youtube.com/watch?v=FE5SmOdrBXY) where Michael literally says "all the major breaking changes are done". rofl
> 
> Yayy congratz! rocket

I'd be very grateful for your contribution! Feel free to make another (draft) PR as soon as you start working on it, then we can all test it and provide feedback.

**Comment by dylviz** [comment]
> > @michaelbromley hey there! Are the data structures for v2 finalized now? Or is there still a pending thing? Sry if that has been answered before, I havent seen it. If it's finalized I'd be down to port this storefront to v2 @kyunal
> > Edit: Just seen the [new Video](https://www.youtube.com/watch?v=FE5SmOdrBXY) where Michael literally says "all the major breaking changes are done". rofl
> > Yayy congratz! rocket
> 
> I'd be very grateful for your contribution! Feel free to make another (draft) PR as soon as you start working on it, then we can all test it and provide feedback.

Let me know if I can contribute to this PR as well. I set some time aside this week to get the front end working with V2 but don't want to create redundant work if it's already being started

**Comment by DanielBiegler** [comment]
@zolzaya  @dylviz I fixed the order history in #44 - Have you encountered problems elsewhere?

Setting the shipping method still works. The type changed to be able to accept an array but string still works too.

**Comment by dylviz** [comment]
> @zolzaya @dylviz I fixed the order history in #44 - Have you encountered problems elsewhere?
> 
> Setting the shipping method still works. The type changed to be able to accept an array but string still works too.

Hi! OK, I will try out. I believe there are quite a few things that need adjustment. If I run `yarn generate` with the new backend, I see about 76 incompatibilities. I can comment feedback on the PR discussion if that's OK.
I also set some time aside this week to work on this so if there's anything I can do to contribute to this PR, just let me know. I'll have time.

**Comment by kyunal** [comment]
Vendure V2 support by @DanielBiegler is merged into https://github.com/vendure-ecommerce/storefront-remix-starter/tree/vendure-v2 until a V2 demo instance is available

**Comment by kyunal** [comment]
Closing this as V2 support is finally merged into the master branch :rocket: 
If anybody's wondering, https://github.com/vendure-ecommerce/storefront-remix-starter/tree/75eb880052d7f76b2026fc917cf545996012e3ac is the last supported commit for V1.
