### ISSUE TITLE
Gracefully handling errors

### ISSUE THREAD

**Issue by DanielBiegler** [vendure-ecommerce/storefront-remix-starter#41]
It can happen that the Server is unreachable for whatever reason and that seems to not be handled at the moment. For example if you dont start the Vendure server you get greeted by this beautiful lil guy:

![image](https://user-images.githubusercontent.com/14810858/233785660-c757747e-55ef-496d-9576-1f6495e14fea.png)

Probably relevant Remix docs [v1](https://remix.run/docs/en/main/route/error-boundary) and [v2](https://remix.run/docs/en/main/route/error-boundary-v2)

How about a simple page saying something like "Oops something went wrong. Please try again soon." with a small image.

Heres how Google does it, short and sweet:

![image](https://user-images.githubusercontent.com/14810858/233785840-36ce0e62-4266-442f-bad1-8b13a92e029b.png)

**Comment by DanielBiegler** [comment]
I'll get this done soon.

**Comment by kyunal** [comment]
That would be great :+1: . Remix makes this really easy to implement, it just wasn't a priority so far.
