### ISSUE TITLE
Prepare for Remix V2

### ISSUE THREAD

**Issue by kyunal** [vendure-ecommerce/storefront-remix-starter#42]
Remix V2 will introduce a couple of breaking changes. Most of them can already be enabled via feature flags in V1 for preparation & testing: https://remix.run/docs/en/main/pages/v2

**Comment by michaelbromley** [comment]
I started updating to Remix v1.19 in preparation for v2, but I ended up breaking things - sessions no longer worked and adding an item to the cart resulted in a page of JSON data of the active order.

I have put my progress so far on this branch: https://github.com/vendure-ecommerce/storefront-remix-starter/tree/update-remix-1.19

If someone with more know-how and patience can take a look, that would be amazing 🙏

**Comment by kyunal** [comment]
Hi Michael,

I'm gonna have a look at things soon when I find the time and hopefully apply some corrections.

**Comment by kyunal** [comment]
Closed as completed in https://github.com/vendure-ecommerce/storefront-remix-starter/commit/961240f0329c5f65a66ceb8103d3b931ec4e0e26
