### ISSUE TITLE
Https certificate on server

### ISSUE THREAD

**Issue by miteshjethmalani** [vendure-ecommerce/storefront-remix-starter#48]
How is the application working with https? Is through express or nginx ?

**Comment by miteshjethmalani** [comment]
@michaelbromley as I have my custom hosting I want to host the application with https

**Comment by kyunal** [comment]
You can serve the application locally by building and then starting it (`yarn build`, `yarn start`). This will expose the application locally through an HTTP server. You can then use a reverse proxy like NGINX or Caddy which and manage HTTPS through them. This is generally preferred to having the application itself deal with HTTPS. This isn't really in the scope of this starter, but there are many great tutorials that can help you set this up. See for instance [setting up NGINX with LetsEncrypt for SSL](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-22-04) and then [configuring it as a reverse proxy](https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-reverse-proxy-on-ubuntu-22-04). Note that these are just some example guides I found.
