### ISSUE TITLE
i18n Translation

### ISSUE THREAD

**Issue by jeancx** [vendure-ecommerce/storefront-remix-starter#56]
Hello, I think it's important to add the option to translate the hard coded texts on template, based on the browser language or fixed by the store owner.

I don't know if you already have plans for this, but I would like to do this using [remix-i18next](https://www.npmjs.com/package/remix-i18next).

I have a project in Brazilian Portuguese, so in addition to making the store i18n, it also helps when I need to merge my code with this repository.

**Comment by kyunal** [comment]
Hi, I don't have plans for this yet, nor have I worked with the library, but contributions are very welcome. I can try to assist here and there with the implementation but I don't think I have the time to do it myself right now unfortunately.

If you want to implement this feature feel free to make a draft PR early in the process so I can look over the work and give feedback :)

**Comment by jeancx** [comment]
I will do and make a PR.
