### ISSUE TITLE
Navbar only show in private browsing

### ISSUE THREAD

**Issue by blackyzero** [vendure-ecommerce/storefront-remix-starter#6]
Hello,

I just did fresh installation, this interface is really fast, however i am getting issue with Navbar, and it only shows in Private browsing, please refer screenshot. This also happens same with your demo site.

<img width="1674" alt="Screen Shot 2022-06-09 at 9 00 33 PM" src="https://user-images.githubusercontent.com/4286063/172969481-06c5f0f2-fb36-4017-822c-9589bd39b041.png">

**Comment by blackyzero** [comment]
i tried on another machine, and it can load properly without Private browsing or Incognito window.

On previous machine, it's still missing nav menu. Browser cache is already clear.

Any idea how to fix it?
Thank you.

**Comment by michaelbromley** [comment]
Is it just the nav menu that is missing? Are the collections showing on the landing page below the big hero image?

**Comment by blackyzero** [comment]
Hi @michaelbromley 

Only nav menu is missing in normal browsing. The big hero and collection can show.

<img width="1668" alt="Screen Shot 2022-06-12 at 10 29 14 AM" src="https://user-images.githubusercontent.com/4286063/173238056-36b8f5a8-dbfc-47fa-8009-d20d292aba7b.png">

Thank you.

**Comment by kyunal** [comment]
@blackyzero Is this issue still recent? I haven't been able to reproduce it.
