### ISSUE TITLE
/sign-up error when running on CloudFlare

### ISSUE THREAD

**Issue by xdabuss** [vendure-ecommerce/storefront-remix-starter#60]
[This](https://github.com/vendure-ecommerce/storefront-remix-starter/blob/master/app/routes/sign-up/index.tsx#L13) line is causing an error in the site when CloudFlare worker tries to access process.env (which CloudFlare workers do not have)

I was able to make the sign-in functionality work by removing lines 13-18. Not sure if there's a way to still keep this "demo url" check in without causing problems for CF?

**Comment by kyunal** [comment]
Hi, I am currently at the Vendure developer meetup, I will get back to you on this and your other issue soon
