### ISSUE TITLE
How to make site usable only for logged in users

### ISSUE THREAD

**Issue by xdabuss** [vendure-ecommerce/storefront-remix-starter#62]
Is there a clever way to "lock" the site so that only logged in users can see anything besides the sign-in page? I've been adding this in all the loaders of each route, but not sure if there's a cleaner/ more robust way?

```
const { activeCustomer } = await getActiveCustomerDetails({ request });
  if (!activeCustomer) {
    return redirect('/sign-in');
  }
```

**Comment by oidt** [comment]
I am not really an export on this topic, but how i tried this:

root.tsx in the loader function:


in the App() function
`if(!loaderData?.activeCustomer?.activeCustomer) {
    return (
<html lang="nl" id="app" translate="no" className="notranslate">
 .....
<main className="">
          <Outlet
              context={{
                activeOrderFetcher,
                activeOrder,
                adjustOrderLine,
                removeItem,
              }}
          />
        </main>
.....
</html>
);
    } else {
    return (
        <html lang="nl" id="app" translate="no" className="notranslate">
<header />
 <main className="">
          <Outlet
              context={{
                activeOrderFetcher,
                activeOrder,
                adjustOrderLine,
                removeItem,
              }}
          />
        </main>
<footer />
</html>
);
}
`

**Comment by parkashay** [comment]
You can just check for activeCustomer in the root loader and redirect to /sign-in if it doesn't exist.

**Comment by xdabuss** [comment]
That makes sense and seems to do the trick, thanks!
