### ISSUE TITLE
Cloudflare Pages returns 404

### ISSUE THREAD

**Issue by vmuneeb** [vendure-ecommerce/storefront-remix-starter#63]
I was able to get it deployed to Cloudflare Pages(I had to select the v1 build system from settings).
Assets also got uploaded 
<img width="856" alt="Screenshot 2024-01-03 at 4 01 27 PM" src="https://github.com/vendure-ecommerce/storefront-remix-starter/assets/6988368/bcca25c8-7f30-418e-beda-830ae3c10cb3">
But the URL is returning 404. 
I think the demo instance provided by the repo is also showing the same behaviour. https://remix-storefront.vendure.io
What could be the issue?
I attempted the same process with Netlify, and encountered the same behavior.

**Comment by kyunal** [comment]
Hi, thanks for the report! I think I found the primary issue: The recent addition of i18n has some node dependencies. I'm working on a fix and hope to push it tomorrow :+1:
