### ISSUE TITLE
How do i pass currency code to vendure Request Context?

### ISSUE THREAD

**Issue by TheValkDokk** [vendure-ecommerce/storefront-remix-starter#79]
Hi, i don't know if i should ask here or in Vendure repo i have a question about how to set the currency code in the header so that the vendure RequestContext can receive the new currency code, in the documents they mentions about using query parameter but it doesn't work

> firstly by any ?currencyCode=XXX query parameter on the request

can someone guide me on this? Much appreciated for your help

**Comment by michaelbromley** [comment]
Hi,

If the request with the `?currencyCode=XXX` is simply not working at all, e.g. even from Postman or some other http client, then that would be an issue you could indeed open in the main Vendure repo.

But if it is the case that somehow the Remix storefront is not actually sending the correct request, we should explore that here and see what is going on. What did you try so far?

**Comment by TheValkDokk** [comment]
Hi, sorry for the late reply, after testing with a fresh build, it's worked, so maybe it's some config on my end, thank you for taking your time to reply
