### ISSUE TITLE
Improve UI and add more features

### ISSUE THREAD

**Issue by blackyzero** [vendure-ecommerce/storefront-remix-starter#8]
Hello,

Thanks for your great project. I know there is a lot of works need to be done.

If possible, please consider to add few more features.

1) Pages content management
2) Products comment or review management

Thanks again.

**Comment by michaelbromley** [comment]
Hi,

Thanks for the feedback! The thing with those two features is that they are not supported by default in Vendure, so it's difficult to know how exactly to implement the storefront part without even knowing what backend API we are going to be using.

My thought is that this starter kit should provide support for all the **default** Vendure functionality, and then anything beyond that like reviews, comments etc would be a matter of customizing the implementation according to your needs.

**Comment by blackyzero** [comment]
got it. Thanks @michaelbromley
